export const LORCANA_SET_LOGOS: Record<string, number> = {
  '1': require('../../assets/lorcana-sets/1.png'),
  '2': require('../../assets/lorcana-sets/2.png'),
  '3': require('../../assets/lorcana-sets/3.png'),
  '4': require('../../assets/lorcana-sets/4.png'),
  '5': require('../../assets/lorcana-sets/5.png'),
  '6': require('../../assets/lorcana-sets/6.png'),
  '7': require('../../assets/lorcana-sets/7.png'),
  '8': require('../../assets/lorcana-sets/8.png'),
  '9': require('../../assets/lorcana-sets/9.png'),
  '10': require('../../assets/lorcana-sets/10.png'),
  '11': require('../../assets/lorcana-sets/11.png'),
  '12': require('../../assets/lorcana-sets/12.png'),
  '13': require('../../assets/lorcana-sets/13.png'),
  '14': require('../../assets/lorcana-sets/14.png'),
  'C2': require('../../assets/lorcana-sets/C2.png'),
  'Q3': require('../../assets/lorcana-sets/Q3.png'),
  'cp': require('../../assets/lorcana-sets/cp.png'),
};
